/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_hse_jnidemo_Native */

#ifndef _Included_ru_hse_jnidemo_Native
#define _Included_ru_hse_jnidemo_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_hse_jnidemo_Native
 * Method:    sayHelloWorld
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ru_hse_jnidemo_Native_sayHelloWorld
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
